### ISSUE TITLE
Create a html , CSS page and use java script for automatic emailing of certificates

### ISSUE THREAD

**Issue by Ayush0922** [GDSC-IIIT-Kalyani/WOC-certificate-generator-Hactoberfest2021#1]
the html page would be a form , which will collect info from user , use a java script code to send the certificate directly to the user who fills the form , via e-mail work pull request should be made in e-mail branch

**Comment by Theskyspace** [comment]
Can I work on this issue?

**Comment by Ayush0922** [comment]
> Can I work on this issue?

go ahead...code and make a pull request on the branch.

**Comment by Theskyspace** [comment]
So to make it clear, I have to make the interface that accepts the details of the user process it using the python script and send the output of the script to the user's email address?
And also make me the assignee

**Comment by Theskyspace** [comment]
And any specific service you want to use with this app. And should I change to flask application if required?

**Comment by Ayush0922** [comment]
> And any specific service you want to use with this app. And should I change to flask application if required?

yes t=it should be a web app and the script should be able to read a csv file , containing  email address , find the certificate by by reading the name , and email it. , making you the assignee

**Comment by Ayush0922** [comment]
> Can I work on this issue?

will assign you this issue after 3rd october.

**Comment by Theskyspace** [comment]
> will assign you this issue after 3rd October.

I have already summited the PR

**Comment by venkat-619** [comment]
hello ayushman can i work on this issue

**Comment by Anmol376OP** [comment]
Please assign me this issue

**Comment by Ayush0922** [comment]
> > will assign you this issue after 3rd October.
> 
> I have already summited the PR

yup it is under review

**Comment by Theskyspace** [comment]
> yup it is under review

Yeah waiting for it to finish.

**Comment by Ayush0922** [comment]
great work @Theskyspace  !!!!
