### ISSUE TITLE
Update Readme (installation guide)

### ISSUE THREAD

**Issue by Theskyspace** [GDSC-IIIT-Kalyani/WOC-certificate-generator-Hactoberfest2021#12]
I will add an installation guide and walkthrough of the application.

**Comment by Ayush0922** [comment]
sure you can , also please keep the title of issue formal, not something like , can i , may i... it doesn't sound very professional.

**Comment by Theskyspace** [comment]
I'll keep that in my mind for the next time

**Comment by Ayush0922** [comment]
completed by @Theskyspace 
gg , nice work.
