### ISSUE TITLE
Need Landing page

### ISSUE THREAD

**Issue by Ayush0922** [GDSC-IIIT-Kalyani/WOC-certificate-generator-Hactoberfest2021#16]
Web app requires a landing page similar in looks to /templates/index.html(check code)
please don't create a css file , add css inside style tag in head.

**Comment by archi-jain** [comment]
Hey!
Can I contribute to this?

**Comment by Ayush0922** [comment]
any progress? @archi-jain  , you asked first , thats the reason i am waiting else , other candidates want to do this, please submit by 1pm (11th october).
