### ISSUE TITLE
README enhancements

### ISSUE THREAD

**Issue by akshitadixit** [GDSC-IIIT-Kalyani/WOC-certificate-generator-Hactoberfest2021#31]
Edit the readme to add the follwowing:
- better installation and setup instructions
- woc logo (can be take from woc2.0-frontend repo)
- readme badges
- contributors

**Comment by venkat-619** [comment]
mam assign me this. i can work on it

**Comment by venkat-619** [comment]
mam readme updated

**Comment by harshit-3103** [comment]
Can I work on this. Please assign me.
