### ISSUE TITLE
Add Documentation & Get started

### ISSUE THREAD

**Issue by Theskyspace** [GDSC-IIIT-Kalyani/WOC-certificate-generator-Hactoberfest2021#4]
Add documentation and setup guide for the project.

**Comment by Theskyspace** [comment]
Can I work on the documentation? If yes kindly mark me as assignee.

**Comment by Ayush0922** [comment]
> Can I work on the documentation? If yes kindly mark me as assignee.

sure go ahead, assigned you this issue.

**Comment by himanshu007-creator** [comment]
@Ayush0922  you are doing a great job man!
Keep it up🎉🟩
