### ISSUE TITLE
Shift the code base to a python flask or web application.

### ISSUE THREAD

**Issue by Ayush0922** [GDSC-IIIT-Kalyani/WOC-certificate-generator-Hactoberfest2021#5]
currently the main driver code of the repo is based on a python driver code , we would like it to change it to a web application or python application with GUI , use any language or resource you like.

**Comment by Apurba-Nath-cpu** [comment]
Please assign this issue to me.

**Comment by Ayush0922** [comment]
> Please assign this issue to me.

go ahead , start working
