### ISSUE TITLE
Change the data colleting path.

### ISSUE THREAD

**Issue by Ayush0922** [GDSC-IIIT-Kalyani/WOC-certificate-generator-Hactoberfest2021#6]
currently the repository reads a csv file to make certificates , instead of that , we would like user(those who are eligible for certificates) to enter their name through a html form or any other mode/method , which eventually gets converted to a certificate and gets saved in the folder.

**Comment by siddharth1704** [comment]
Can we add the feature we take data through html and add it to csv file?

**Comment by siddharth1704** [comment]
If yes i would like to take this issue so can you assign it to me

**Comment by Ayush0922** [comment]
> If yes i would like to take this issue so can you assign it to me

ok , assigning you

**Comment by siddharth1704** [comment]
Hey @Ayush0922  i was thinking to save the html form  data to a google sheets that can be used by the `main.py` to convert it into a certificate and save it. If thats fine with you otherwise we can setup a flask backend for it.

**Comment by siddharth1704** [comment]
Ok simply we can save the data in google sheet and then use python library to fetch it to `main.py` for making the certificates

**Comment by Ayush0922** [comment]
> Hey @Ayush0922 i was thinking to save the html form data to a google sheets that can be used by the `main.py` to convert it into a certificate and save it. If thats fine with you otherwise we can setup a flask backend for it.

both sound good , do as you are comfortable also make pull request into email 2.0 branch , fork again if you want.

**Comment by Ayush0922** [comment]
Issue resolved by other person.
